name: 'judicial_dw'
version: '1.0.0'
config-version: 2

profile: 'judicial_dw'

model-paths: ["models"]
test-paths:  ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  judicial_dw:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +tags: ["mart", "court"]
